name: Run Android Linter workflow

on: [workflow_call]

jobs:
  lint:
    name: Run Android Linter
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Run Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: lint

    - name: Upload Markdown Report
      run: |
        echo "<details>" >> $GITHUB_STEP_SUMMARY
        echo "<summary>Show Report</summary>" >> $GITHUB_STEP_SUMMARY
        sed -n '/<body/,/<\/body>/p' **/build/reports/lint-results-debug.html >> $GITHUB_STEP_SUMMARY
        echo "</details>" >> $GITHUB_STEP_SUMMARY
      if: success() || failure()

    - name: Upload HTML Reports
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: Lint-HTML
        path: '**/build/reports/lint-results-debug.html'
