name: Run Detekt Linter workflow

on:
  workflow_call:
    inputs:
      upload_sarif:
        default: false
        type: boolean

jobs:
  detekt:
    name: Run Detekt Linter
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Run Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: detekt

    - name: Upload Markdown Report
      run: |
        echo "<details>" >> $GITHUB_STEP_SUMMARY
        echo "<summary>Show Report</summary>" >> $GITHUB_STEP_SUMMARY
        cat build/reports/detekt/detekt.md >> $GITHUB_STEP_SUMMARY
        echo "</details>" >> $GITHUB_STEP_SUMMARY
      if: success() || failure()

    - name: Upload HTML Reports
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: Detekt-HTML
        path: build/reports/detekt/detekt.html

    - name: Upload SARIF Report
      uses: github/codeql-action/upload-sarif@v3
      if: inputs.upload_sarif && (success() || failure())
      with:
        sarif_file: build/reports/detekt/detekt.sarif
